/*
 * mcal_interrupt_gen_cfg.h
 *
 * Created: 1/20/2024 10:58:34 PM
 *  Author: LENOVO
 */ 


#ifndef MCAL_INTERRUPT_GEN_CFG_H_
#define MCAL_INTERRUPT_GEN_CFG_H_

#define TIMER0_INTERRUPT_FEATURE_ENABLE             INTERRUPT_FEATURE_ENABLE
#define TIMER1_INTERRUPT_FEATURE_ENABLE             INTERRUPT_FEATURE_ENABLE
#define TIMER2_INTERRUPT_FEATURE_ENABLE             INTERRUPT_FEATURE_ENABLE



#endif /* MCAL_INTERRUPT_GEN_CFG_H_ */